name: Deploy to EKS

on:
  workflow_dispatch:   # Allows manual triggering
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'DEV'
        type: choice
        options: ['DEV', 'QA', 'PRD']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
