name: using multiple jobs in workflow
on:
  push
jobs:
   build_job:
    runs-on: ubuntu-latest
    steps:
    - name: install java
      run: sudo apt install default-jdk
    - name: execute java command
      run: java --version >> test.txt
    - name: upload text file
      uses: actions/upload-artifact@v4
      with:
        name: text-file
        path: test.txt
   test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
    - name: download text file
      uses: actions/download-artifact@v4
      with:
        name: text-file
        path: test.txt
    - name: Check file content
      run: grep -i -r "test" test.txt || true 


   deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
    - name: download text file
      uses: actions/download-artifact@v4
      with:
        name: text-file
        path: test.txt
    - name: read file
      run: cat test.txt