name: using multiple jobs in workflow
on:
  push
jobs:
   build_job:
    runs-on: ubuntu-latest
    steps:
    - name: install java
      run: sudo apt install default-jdk
    - name: execute java command
      run: java --version >> test.txt
   test_job:
     needs: build_job
     runs-on: ubuntu-latest
     steps:
     - name: check file exist
       run: grep -i "test" test.txt
   deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
    - name: read file
      run: cat dragon.txt